import { db } from "./index";
import { parts, thrustTestData } from "./schema";
import { sql } from "drizzle-orm";
import * as fs from "fs";
import * as path from "path";

async function main() {
  console.log("Seeding database...");

  // Disable foreign keys during seeding to allow clearing and reloading parts
  await db.run(sql`PRAGMA foreign_keys = OFF;`);

  try {
    // We can't easily truncate because of foreign keys, so we delete in order
    await db.delete(thrustTestData);
    await db.delete(parts);
    console.log("Cleared existing parts and thrust test data.");
  } catch (err) {
    console.log("No previous tables to clear or error clearing: ", err);
  }

  // 2. Insert Parts
  const seededParts = [
    // ─── FRAMES (7 parts) ──────────────────────────────────────────────────────
    {
      id: "frame-mob7",
      name: "Mobula7 V2 75mm Brushless Whoop Frame",
      manufacturer: "HappyModel",
      model: "Mobula7 V2",
      weightGrams: 5.5,
      mainCategory: "FRAME" as const,
      subCategory: "FRAME" as const,
      isComposite: false,
      integratedPartIds: [],
      isArchived: false,
      attributes: {
        wheelbaseMm: 75.0,
        armThicknessMm: 1.0,
        maxPropSizeInch: 1.6, // 40mm props
        fcMountingPattern: ["25.5x25.5"],
        motorMountingPattern: ["three-hole-6.6mm"],
        vtxMountingPattern: [],
        stackHeightMaxMm: 15.0,
        topPlatePresent: false,
      },
    },
    {
      id: "frame-cinelog35",
      name: "Cinelog35 V2 Freestyle CineWhoop Frame",
      manufacturer: "GepRC",
      model: "Cinelog35 V2",
      weightGrams: 116.0,
      mainCategory: "FRAME" as const,
      subCategory: "FRAME" as const,
      isComposite: false,
      integratedPartIds: [],
      isArchived: false,
      attributes: {
        wheelbaseMm: 142.0,
        armThicknessMm: 3.5,
        maxPropSizeInch: 3.5,
        fcMountingPattern: ["20x20", "25.5x25.5"],
        motorMountingPattern: ["12x12"],
        vtxMountingPattern: ["20x20", "25.5x25.5"],
        stackHeightMaxMm: 28.0,
        topPlatePresent: true,
      },
    },
    {
      id: "frame-apex5",
      name: "Apex 5\" Freestyle Frame",
      manufacturer: "ImpulseRC",
      model: "Apex 5",
      weightGrams: 125.0,
      mainCategory: "FRAME" as const,
      subCategory: "FRAME" as const,
      isComposite: false,
      integratedPartIds: [],
      isArchived: false,
      attributes: {
        wheelbaseMm: 225.0,
        armThicknessMm: 5.5,
        maxPropSizeInch: 5.1,
        fcMountingPattern: ["20x20", "30.5x30.5"],
        motorMountingPattern: ["16x16"],
        vtxMountingPattern: ["20x20", "30.5x30.5"],
        stackHeightMaxMm: 25.0,
        topPlatePresent: true,
      },
    },
    {
      id: "frame-bee35",
      name: "SpeedyBee Bee35 CineWhoop Frame",
      manufacturer: "SpeedyBee",
      model: "Bee35",
      weightGrams: 138.0,
      mainCategory: "FRAME" as const,
      subCategory: "FRAME" as const,
      isComposite: false,
      integratedPartIds: [],
      isArchived: false,
      attributes: {
        wheelbaseMm: 153.0,
        armThicknessMm: 3.0,
        maxPropSizeInch: 3.5,
        fcMountingPattern: ["20x20", "25.5x25.5", "30.5x30.5"],
        motorMountingPattern: ["12x12"],
        vtxMountingPattern: ["20x20", "25.5x25.5"],
        stackHeightMaxMm: 26.0,
        topPlatePresent: true,
      },
    },
    {
      id: "frame-nazgul5",
      name: "Nazgul Evoque F5D DeadCat Frame",
      manufacturer: "iFlight",
      model: "Nazgul Evoque F5D",
      weightGrams: 150.0,
      mainCategory: "FRAME" as const,
      subCategory: "FRAME" as const,
      isComposite: false,
      integratedPartIds: [],
      isArchived: false,
      attributes: {
        wheelbaseMm: 223.0,
        armThicknessMm: 6.0,
        maxPropSizeInch: 5.1,
        fcMountingPattern: ["20x20", "30.5x30.5"],
        motorMountingPattern: ["16x16"],
        vtxMountingPattern: ["20x20", "25.5x25.5"],
        stackHeightMaxMm: 22.0,
        topPlatePresent: true,
      },
    },
    {
      id: "frame-flywoo4",
      name: "Explorer LR 4 Frame V2",
      manufacturer: "Flywoo",
      model: "Explorer LR 4 V2",
      weightGrams: 41.0,
      mainCategory: "FRAME" as const,
      subCategory: "FRAME" as const,
      isComposite: false,
      integratedPartIds: [],
      isArchived: false,
      attributes: {
        wheelbaseMm: 168.0,
        armThicknessMm: 3.0,
        maxPropSizeInch: 4.0,
        fcMountingPattern: ["16x16", "20x20"],
        motorMountingPattern: ["9x9", "12x12"],
        vtxMountingPattern: ["20x20"],
        stackHeightMaxMm: 20.0,
        topPlatePresent: true,
      },
    },
    {
      id: "frame-chimera7",
      name: "Chimera7 Pro V2 Long Range Frame",
      manufacturer: "iFlight",
      model: "Chimera7 Pro V2",
      weightGrams: 290.0,
      mainCategory: "FRAME" as const,
      subCategory: "FRAME" as const,
      isComposite: false,
      integratedPartIds: [],
      isArchived: false,
      attributes: {
        wheelbaseMm: 320.0,
        armThicknessMm: 6.0,
        maxPropSizeInch: 7.5,
        fcMountingPattern: ["30.5x30.5"],
        motorMountingPattern: ["19x19"],
        vtxMountingPattern: ["20x20", "30.5x30.5"],
        stackHeightMaxMm: 29.0,
        topPlatePresent: true,
      },
    },

    // ─── FLIGHT CONTROLLERS (4 parts) ──────────────────────────────────────────
    {
      id: "fc-speedybeef405",
      name: "SpeedyBee F405 V3 Flight Controller",
      manufacturer: "SpeedyBee",
      model: "F405 V3",
      weightGrams: 9.6,
      mainCategory: "ELECTRONICS" as const,
      subCategory: "FC" as const,
      isComposite: false,
      integratedPartIds: [],
      isArchived: false,
      attributes: {
        mountingPattern: "30.5x30.5",
        inputVoltagesMax: 6,
        firmware: "Betaflight",
        gyro: "BMI270",
        mcu: "F4",
        uartCount: 6,
        hasBarometer: true,
        hasBluetooth: true,
        hasBec: true,
      },
    },
    {
      id: "fc-blitzf7",
      name: "Blitz F7 V2 Flight Controller",
      manufacturer: "iFlight",
      model: "Blitz F7 V2",
      weightGrams: 8.5,
      mainCategory: "ELECTRONICS" as const,
      subCategory: "FC" as const,
      isComposite: false,
      integratedPartIds: [],
      isArchived: false,
      attributes: {
        mountingPattern: "30.5x30.5",
        inputVoltagesMax: 8,
        firmware: "Betaflight",
        gyro: "ICM-42688-P",
        mcu: "F7",
        uartCount: 6,
        hasBarometer: true,
        hasBluetooth: false,
        hasBec: true,
      },
    },
    {
      id: "fc-matekh743",
      name: "Matek H743-WING V3 Flight Controller",
      manufacturer: "Matek Systems",
      model: "H743-WING V3",
      weightGrams: 26.0,
      mainCategory: "ELECTRONICS" as const,
      subCategory: "FC" as const,
      isComposite: false,
      integratedPartIds: [],
      isArchived: false,
      attributes: {
        mountingPattern: "30.5x30.5",
        inputVoltagesMax: 8,
        firmware: "iNav",
        gyro: "ICM-42688-P",
        mcu: "H7",
        uartCount: 8,
        hasBarometer: true,
        hasBluetooth: false,
        hasBec: true,
      },
    },
    {
      id: "fc-kakuteh7",
      name: "Holybro Kakute H7 V2 Flight Controller",
      manufacturer: "Holybro",
      model: "Kakute H7 V2",
      weightGrams: 8.0,
      mainCategory: "ELECTRONICS" as const,
      subCategory: "FC" as const,
      isComposite: false,
      integratedPartIds: [],
      isArchived: false,
      attributes: {
        mountingPattern: "30.5x30.5",
        inputVoltagesMax: 6,
        firmware: "Betaflight",
        gyro: "BMI270",
        mcu: "H7",
        uartCount: 6,
        hasBarometer: true,
        hasBluetooth: true,
        hasBec: true,
      },
    },

    // ─── SPEED CONTROLLERS (6 parts) ───────────────────────────────────────────
    {
      id: "esc-speedybee50",
      name: "SpeedyBee 50A BLHeli_S 4-in-1 ESC",
      manufacturer: "SpeedyBee",
      model: "50A 4-in-1",
      weightGrams: 15.0,
      mainCategory: "ELECTRONICS" as const,
      subCategory: "ESC" as const,
      isComposite: false,
      integratedPartIds: [],
      isArchived: false,
      attributes: {
        continuousCurrentAmps: 50.0,
        burstCurrentAmps: 60.0,
        mountingPattern: "30.5x30.5",
        inputVoltagesMax: 6,
        firmware: "BLHeli_S",
        motorOutputCount: 4,
        hasTelemetry: false,
      },
    },
    {
      id: "esc-blitz55",
      name: "iFlight Blitz E55S 4-in-1 ESC",
      manufacturer: "iFlight",
      model: "Blitz E55S",
      weightGrams: 16.5,
      mainCategory: "ELECTRONICS" as const,
      subCategory: "ESC" as const,
      isComposite: false,
      integratedPartIds: [],
      isArchived: false,
      attributes: {
        continuousCurrentAmps: 55.0,
        burstCurrentAmps: 65.0,
        mountingPattern: "30.5x30.5",
        inputVoltagesMax: 6,
        firmware: "BLHeli_32",
        motorOutputCount: 4,
        hasTelemetry: true,
      },
    },
    {
      id: "esc-tmotor45",
      name: "T-Motor F45A V2 4-in-1 ESC",
      manufacturer: "T-Motor",
      model: "F45A V2",
      weightGrams: 18.0,
      mainCategory: "ELECTRONICS" as const,
      subCategory: "ESC" as const,
      isComposite: false,
      integratedPartIds: [],
      isArchived: false,
      attributes: {
        continuousCurrentAmps: 45.0,
        burstCurrentAmps: 55.0,
        mountingPattern: "30.5x30.5",
        inputVoltagesMax: 6,
        firmware: "BLHeli_32",
        motorOutputCount: 4,
        hasTelemetry: true,
      },
    },
    {
      id: "esc-tekko65",
      name: "Holybro Tekko32 F4 4-in-1 65A ESC",
      manufacturer: "Holybro",
      model: "Tekko32 65A",
      weightGrams: 22.0,
      mainCategory: "ELECTRONICS" as const,
      subCategory: "ESC" as const,
      isComposite: false,
      integratedPartIds: [],
      isArchived: false,
      attributes: {
        continuousCurrentAmps: 65.0,
        burstCurrentAmps: 80.0,
        mountingPattern: "30.5x30.5",
        inputVoltagesMax: 6,
        firmware: "BLHeli_32",
        motorOutputCount: 4,
        hasTelemetry: true,
      },
    },
    {
      id: "esc-reaper60",
      name: "Foxeer Reaper Extreme 60A 4-in-1 ESC",
      manufacturer: "Foxeer",
      model: "Reaper Extreme 60A",
      weightGrams: 18.0,
      mainCategory: "ELECTRONICS" as const,
      subCategory: "ESC" as const,
      isComposite: false,
      integratedPartIds: [],
      isArchived: false,
      attributes: {
        continuousCurrentAmps: 60.0,
        burstCurrentAmps: 70.0,
        mountingPattern: "30.5x30.5",
        inputVoltagesMax: 8,
        firmware: "AM32",
        motorOutputCount: 4,
        hasTelemetry: true,
      },
    },
    {
      id: "esc-zeus35",
      name: "HGLRC Zeus 35A 4-in-1 ESC",
      manufacturer: "HGLRC",
      model: "Zeus 35A",
      weightGrams: 9.8,
      mainCategory: "ELECTRONICS" as const,
      subCategory: "ESC" as const,
      isComposite: false,
      integratedPartIds: [],
      isArchived: false,
      attributes: {
        continuousCurrentAmps: 35.0,
        burstCurrentAmps: 40.0,
        mountingPattern: "20x20",
        inputVoltagesMax: 6,
        firmware: "BLHeli_S",
        motorOutputCount: 4,
        hasTelemetry: false,
      },
    },

     // ─── ALL IN ONE (AIO) BOARDS (4 parts) ─────────────────────────────────────
    {
      id: "aio-superx",
      name: "HappyModel SuperX HD ELRS 1-2S AIO",
      manufacturer: "HappyModel",
      model: "SuperX HD ELRS",
      weightGrams: 5.6,
      mainCategory: "ELECTRONICS" as const,
      subCategory: "AIO" as const,
      isComposite: true,
      integratedPartIds: [], // virtual composition is self-described via attributes
      isArchived: false,
      attributes: {
        // Combined FC + ESC fields
        mountingPattern: "25.5x25.5",
        inputVoltagesMax: 2,
        firmware: "Betaflight",
        gyro: "ICM-42688-P",
        mcu: "F4",
        uartCount: 2,
        hasBarometer: false,
        hasBluetooth: false,
        continuousCurrentAmps: 12.0,
        burstCurrentAmps: 15.0,
        escFirmware: "Bluejay",
        motorOutputCount: 4,
        hasTelemetry: false,
        hasBec: true,
      },
    },
    {
      id: "aio-betafpv12",
      name: "BetaFPV F4 1S 12A Brushless AIO",
      manufacturer: "BetaFPV",
      model: "F4 1S 12A AIO",
      weightGrams: 4.5,
      mainCategory: "ELECTRONICS" as const,
      subCategory: "AIO" as const,
      isComposite: true,
      integratedPartIds: [],
      isArchived: false,
      attributes: {
        mountingPattern: "25.5x25.5",
        inputVoltagesMax: 1,
        firmware: "Betaflight",
        gyro: "BMI270",
        mcu: "F4",
        uartCount: 2,
        hasBarometer: false,
        hasBluetooth: false,
        continuousCurrentAmps: 12.0,
        burstCurrentAmps: 15.0,
        escFirmware: "Bluejay",
        motorOutputCount: 4,
        hasTelemetry: false,
        hasBec: true,
      },
    },
    {
      id: "aio-darwin15",
      name: "DarwinFPV 15A 1-3S F411 AIO",
      manufacturer: "DarwinFPV",
      model: "Darwin 15A AIO",
      weightGrams: 5.5,
      mainCategory: "ELECTRONICS" as const,
      subCategory: "AIO" as const,
      isComposite: true,
      integratedPartIds: [],
      isArchived: false,
      attributes: {
        mountingPattern: "25.5x25.5",
        inputVoltagesMax: 3,
        firmware: "Betaflight",
        gyro: "BMI270",
        mcu: "F4",
        uartCount: 2,
        hasBarometer: false,
        hasBluetooth: false,
        continuousCurrentAmps: 15.0,
        burstCurrentAmps: 18.0,
        escFirmware: "BLHeli_S",
        motorOutputCount: 4,
        hasTelemetry: false,
        hasBec: true,
      },
    },
    {
      id: "aio-taker35",
      name: "GepRC Taker G4 35A AIO V2",
      manufacturer: "GepRC",
      model: "Taker G4 35A",
      weightGrams: 8.5,
      mainCategory: "ELECTRONICS" as const,
      subCategory: "AIO" as const,
      isComposite: true,
      integratedPartIds: [],
      isArchived: false,
      attributes: {
        mountingPattern: "25.5x25.5",
        inputVoltagesMax: 6,
        firmware: "Betaflight",
        gyro: "ICM-42688-P",
        mcu: "F4", // G4 is similar processing class
        uartCount: 4,
        hasBarometer: true,
        hasBluetooth: false,
        continuousCurrentAmps: 35.0,
        burstCurrentAmps: 40.0,
        escFirmware: "Bluejay",
        motorOutputCount: 4,
        hasTelemetry: true,
        hasBec: true,
      },
    },

    // ─── MOTORS (8 parts) ──────────────────────────────────────────────────────
    {
      id: "motor-se0802",
      name: "SE0802 19000KV Brushless Motor",
      manufacturer: "HappyModel",
      model: "SE0802",
      weightGrams: 1.9,
      mainCategory: "PROPULSION" as const,
      subCategory: "MOTOR" as const,
      isComposite: false,
      integratedPartIds: [],
      isArchived: false,
      attributes: {
        kv: 19000,
        statorDiameterMm: 8.0,
        statorHeightMm: 2.0,
        mountingPattern: "three-hole-6.6mm",
        propMountingPattern: ["1.5mm"],
        inputVoltageMax: 4.35, // 1S
        maxCurrentDraw: 6.0,
      },
    },
    {
      id: "motor-xing2207-1850",
      name: "XING2 2207 1850KV Unibell Motor",
      manufacturer: "iFlight",
      model: "XING2 2207 1850KV",
      weightGrams: 31.6,
      mainCategory: "PROPULSION" as const,
      subCategory: "MOTOR" as const,
      isComposite: false,
      integratedPartIds: [],
      isArchived: false,
      attributes: {
        kv: 1850,
        statorDiameterMm: 22.0,
        statorHeightMm: 7.0,
        mountingPattern: "16x16",
        propMountingPattern: ["5mm"],
        inputVoltageMax: 25.2, // 6S
        maxCurrentDraw: 45.0,
      },
    },
    {
      id: "motor-xing2207-2750",
      name: "XING2 2207 2750KV Unibell Motor",
      manufacturer: "iFlight",
      model: "XING2 2207 2750KV",
      weightGrams: 31.6,
      mainCategory: "PROPULSION" as const,
      subCategory: "MOTOR" as const,
      isComposite: false,
      integratedPartIds: [],
      isArchived: false,
      attributes: {
        kv: 2750,
        statorDiameterMm: 22.0,
        statorHeightMm: 7.0,
        mountingPattern: "16x16",
        propMountingPattern: ["5mm"],
        inputVoltageMax: 16.8, // 4S
        maxCurrentDraw: 52.0,
      },
    },
    {
      id: "motor-xing1404",
      name: "XING 1404 4600KV Ultralight Motor",
      manufacturer: "iFlight",
      model: "XING 1404",
      weightGrams: 9.3,
      mainCategory: "PROPULSION" as const,
      subCategory: "MOTOR" as const,
      isComposite: false,
      integratedPartIds: [],
      isArchived: false,
      attributes: {
        kv: 4600,
        statorDiameterMm: 14.0,
        statorHeightMm: 4.0,
        mountingPattern: "9x9",
        propMountingPattern: ["1.5mm"],
        inputVoltageMax: 16.8, // 4S
        maxCurrentDraw: 18.0,
      },
    },
    {
      id: "motor-bh1504",
      name: "VY 1504.5 3950KV Brushless Motor",
      manufacturer: "BrotherHobby",
      model: "VY 1504.5",
      weightGrams: 12.0,
      mainCategory: "PROPULSION" as const,
      subCategory: "MOTOR" as const,
      isComposite: false,
      integratedPartIds: [],
      isArchived: false,
      attributes: {
        kv: 3950,
        statorDiameterMm: 15.0,
        statorHeightMm: 4.5,
        mountingPattern: "12x12",
        propMountingPattern: ["1.5mm", "5mm"],
        inputVoltageMax: 16.8, // 4S
        maxCurrentDraw: 22.0,
      },
    },
    {
      id: "motor-eco2807",
      name: "ECO II 2807 1300KV Motor",
      manufacturer: "EMAX",
      model: "ECO II 2807",
      weightGrams: 48.0,
      mainCategory: "PROPULSION" as const,
      subCategory: "MOTOR" as const,
      isComposite: false,
      integratedPartIds: [],
      isArchived: false,
      attributes: {
        kv: 1300,
        statorDiameterMm: 28.0,
        statorHeightMm: 7.0,
        mountingPattern: "19x19",
        propMountingPattern: ["5mm"],
        inputVoltageMax: 25.2, // 6S
        maxCurrentDraw: 55.0,
      },
    },
    {
      id: "motor-velox2207",
      name: "Velox V3 2207 1950KV Motor",
      manufacturer: "T-Motor",
      model: "Velox V3 2207",
      weightGrams: 32.1,
      mainCategory: "PROPULSION" as const,
      subCategory: "MOTOR" as const,
      isComposite: false,
      integratedPartIds: [],
      isArchived: false,
      attributes: {
        kv: 1950,
        statorDiameterMm: 22.0,
        statorHeightMm: 7.0,
        mountingPattern: "16x16",
        propMountingPattern: ["5mm"],
        inputVoltageMax: 25.2, // 6S
        maxCurrentDraw: 48.0,
      },
    },
    {
      id: "motor-f40pro",
      name: "F40 PRO IV 1950KV FPV Motor",
      manufacturer: "T-Motor",
      model: "F40 PRO IV",
      weightGrams: 30.8,
      mainCategory: "PROPULSION" as const,
      subCategory: "MOTOR" as const,
      isComposite: false,
      integratedPartIds: [],
      isArchived: false,
      attributes: {
        kv: 1950,
        statorDiameterMm: 22.0,
        statorHeightMm: 7.0,
        mountingPattern: "16x16",
        propMountingPattern: ["5mm"],
        inputVoltageMax: 25.2, // 6S
        maxCurrentDraw: 51.0,
      },
    },

    // ─── PROPELLERS (6 parts) ──────────────────────────────────────────────────
    {
      id: "prop-gemfan1635",
      name: "Gemfan 1635 40mm 4-Blade Propellers (Set of 4)",
      manufacturer: "Gemfan",
      model: "1635-4",
      weightGrams: 0.5, // single prop weight
      mainCategory: "PROPULSION" as const,
      subCategory: "PROPELLER" as const,
      isComposite: false,
      integratedPartIds: [],
      isArchived: false,
      attributes: {
        diameterInch: 1.6,
        pitchInch: 1.5,
        mountingPattern: ["1.5mm"],
        blades: 4,
      },
    },
    {
      id: "prop-gemfan51433",
      name: "Gemfan Hurricane 51433 3-Blade Propeller",
      manufacturer: "Gemfan",
      model: "Hurricane 51433",
      weightGrams: 3.8,
      mainCategory: "PROPULSION" as const,
      subCategory: "PROPELLER" as const,
      isComposite: false,
      integratedPartIds: [],
      isArchived: false,
      attributes: {
        diameterInch: 5.1,
        pitchInch: 4.3,
        mountingPattern: ["5mm"],
        blades: 3,
      },
    },
    {
      id: "prop-ethixs3",
      name: "HQProp Ethix S3 Watermelon 5x3.1x3 Propeller",
      manufacturer: "HQProp",
      model: "Ethix S3",
      weightGrams: 3.6,
      mainCategory: "PROPULSION" as const,
      subCategory: "PROPELLER" as const,
      isComposite: false,
      integratedPartIds: [],
      isArchived: false,
      attributes: {
        diameterInch: 5.0,
        pitchInch: 3.1,
        mountingPattern: ["5mm"],
        blades: 3,
      },
    },
    {
      id: "prop-hq3.5",
      name: "HQProp T3.5x2.5x3 3-Blade Propeller",
      manufacturer: "HQProp",
      model: "T3.5x2.5x3",
      weightGrams: 1.5,
      mainCategory: "PROPULSION" as const,
      subCategory: "PROPELLER" as const,
      isComposite: false,
      integratedPartIds: [],
      isArchived: false,
      attributes: {
        diameterInch: 3.5,
        pitchInch: 2.5,
        mountingPattern: ["5mm", "1.5mm"],
        blades: 3,
      },
    },
    {
      id: "prop-gemfan3018",
      name: "Gemfan Hurricane 3018 2-Blade Propeller",
      manufacturer: "Gemfan",
      model: "Hurricane 3018",
      weightGrams: 0.8,
      mainCategory: "PROPULSION" as const,
      subCategory: "PROPELLER" as const,
      isComposite: false,
      integratedPartIds: [],
      isArchived: false,
      attributes: {
        diameterInch: 3.0,
        pitchInch: 1.8,
        mountingPattern: ["1.5mm"],
        blades: 2,
      },
    },
    {
      id: "prop-hq7",
      name: "HQProp 7x3.5x3 3-Blade Propeller",
      manufacturer: "HQProp",
      model: "7x3.5x3",
      weightGrams: 8.5,
      mainCategory: "PROPULSION" as const,
      subCategory: "PROPELLER" as const,
      isComposite: false,
      integratedPartIds: [],
      isArchived: false,
      attributes: {
        diameterInch: 7.0,
        pitchInch: 3.5,
        mountingPattern: ["5mm"],
        blades: 3,
      },
    },

    // ─── BATTERIES (6 parts) ───────────────────────────────────────────────────
    {
      id: "bat-tattu1300-6s",
      name: "Tattu R-Line Version 5.0 6S 1300mAh 150C LiPo",
      manufacturer: "Tattu",
      model: "R-Line V5 6S 1300mAh",
      weightGrams: 220.0,
      mainCategory: "PROPULSION" as const,
      subCategory: "BATTERY" as const,
      isComposite: false,
      integratedPartIds: [],
      isArchived: false,
      attributes: {
        cellCount: 6,
        capacityMah: 1300.0,
        cRating: 150,
        chemistry: "LiPo",
      },
    },
    {
      id: "bat-gnb450-1s",
      name: "GNB 1S 450mAh 100C 3.8V LiHv",
      manufacturer: "GNB",
      model: "GNB 1S 450mAh LiHv",
      weightGrams: 13.0,
      mainCategory: "PROPULSION" as const,
      subCategory: "BATTERY" as const,
      isComposite: false,
      integratedPartIds: [],
      isArchived: false,
      attributes: {
        cellCount: 1,
        capacityMah: 450.0,
        cRating: 100,
        chemistry: "LiHv",
      },
    },
    {
      id: "bat-tattu850-4s",
      name: "Tattu R-Line 4S 850mAh 95C LiPo",
      manufacturer: "Tattu",
      model: "R-Line 4S 850mAh",
      weightGrams: 102.0,
      mainCategory: "PROPULSION" as const,
      subCategory: "BATTERY" as const,
      isComposite: false,
      integratedPartIds: [],
      isArchived: false,
      attributes: {
        cellCount: 4,
        capacityMah: 850.0,
        cRating: 95,
        chemistry: "LiPo",
      },
    },
    {
      id: "bat-aulink4000-6s",
      name: "Aulink 6S 4000mAh 10C 18650 LiIon Pack",
      manufacturer: "Aulink",
      model: "6S 4000mAh LiIon",
      weightGrams: 300.0,
      mainCategory: "PROPULSION" as const,
      subCategory: "BATTERY" as const,
      isComposite: false,
      integratedPartIds: [],
      isArchived: false,
      attributes: {
        cellCount: 6,
        capacityMah: 4000.0,
        cRating: 10,
        chemistry: "LiIon",
      },
    },
    {
      id: "bat-cnhl1500-4s",
      name: "CNHL Black Series 4S 1500mAh 100C LiPo",
      manufacturer: "CNHL",
      model: "Black Series 4S 1500mAh",
      weightGrams: 185.0,
      mainCategory: "PROPULSION" as const,
      subCategory: "BATTERY" as const,
      isComposite: false,
      integratedPartIds: [],
      isArchived: false,
      attributes: {
        cellCount: 4,
        capacityMah: 1500.0,
        cRating: 100,
        chemistry: "LiPo",
      },
    },
    {
      id: "bat-gnb650-2s",
      name: "GNB 2S 650mAh 90C LiPo",
      manufacturer: "GNB",
      model: "GNB 2S 650mAh",
      weightGrams: 36.0,
      mainCategory: "PROPULSION" as const,
      subCategory: "BATTERY" as const,
      isComposite: false,
      integratedPartIds: [],
      isArchived: false,
      attributes: {
        cellCount: 2,
        capacityMah: 650.0,
        cRating: 90,
        chemistry: "LiPo",
      },
    },

    // ─── VIDEO TRANSMITTERS (VTX) (4 parts) ───────────────────────────────────
    {
      id: "vtx-djio3",
      name: "DJI O3 Air Unit VTX",
      manufacturer: "DJI",
      model: "O3 Air Unit",
      weightGrams: 39.0, // VTX + camera combined weight
      mainCategory: "ELECTRONICS" as const,
      subCategory: "VTX" as const,
      isComposite: false,
      integratedPartIds: [],
      isArchived: false,
      attributes: {
        inputVoltageMin: 7.4,
        inputVoltageMax: 26.4,
        mountingPattern: ["20x20"],
        maxPowerMw: 1000,
        protocol: "DJI O3",
      },
    },
    {
      id: "vtx-walksnail",
      name: "Walksnail Avatar V2 VTX",
      manufacturer: "Caddx",
      model: "Avatar V2 VTX",
      weightGrams: 18.0,
      mainCategory: "ELECTRONICS" as const,
      subCategory: "VTX" as const,
      isComposite: false,
      integratedPartIds: [],
      isArchived: false,
      attributes: {
        inputVoltageMin: 6.0,
        inputVoltageMax: 25.2,
        mountingPattern: ["20x20", "25.5x25.5"],
        maxPowerMw: 1200,
        protocol: "Avatar",
      },
    },
    {
      id: "vtx-hdzerolite",
      name: "HDZero Whoop Lite VTX",
      manufacturer: "Divimath",
      model: "HDZero Whoop Lite",
      weightGrams: 4.5,
      mainCategory: "ELECTRONICS" as const,
      subCategory: "VTX" as const,
      isComposite: false,
      integratedPartIds: [],
      isArchived: false,
      attributes: {
        inputVoltageMin: 3.3,
        inputVoltageMax: 5.5, // powered from 5V regulator
        mountingPattern: ["25.5x25.5"],
        maxPowerMw: 200,
        protocol: "HDZero",
      },
    },
    {
      id: "vtx-tbsunify",
      name: "TBS Unify Pro32 Nano 5G8 (Analog)",
      manufacturer: "TBS",
      model: "Unify Pro32 Nano",
      weightGrams: 1.0,
      mainCategory: "ELECTRONICS" as const,
      subCategory: "VTX" as const,
      isComposite: false,
      integratedPartIds: [],
      isArchived: false,
      attributes: {
        inputVoltageMin: 3.0,
        inputVoltageMax: 13.0,
        mountingPattern: [],
        maxPowerMw: 500,
        protocol: "Analog",
      },
    },

    // ─── RC RECEIVERS (4 parts) ────────────────────────────────────────────────
    {
      id: "rx-ep1",
      name: "HappyModel EP1 RX ELRS 2.4GHz Receiver",
      manufacturer: "HappyModel",
      model: "EP1 RX",
      weightGrams: 0.4,
      mainCategory: "ELECTRONICS" as const,
      subCategory: "RC_RECEIVER" as const,
      isComposite: false,
      integratedPartIds: [],
      isArchived: false,
      attributes: {},
    },
    {
      id: "rx-crossfire",
      name: "TBS Crossfire Nano RX",
      manufacturer: "TBS",
      model: "Crossfire Nano RX",
      weightGrams: 0.5,
      mainCategory: "ELECTRONICS" as const,
      subCategory: "RC_RECEIVER" as const,
      isComposite: false,
      integratedPartIds: [],
      isArchived: false,
      attributes: {},
    },
    {
      id: "rx-elrslite",
      name: "BetaFPV ELRS Lite RX (Flat Ceramic Antenna)",
      manufacturer: "BetaFPV",
      model: "ELRS Lite RX",
      weightGrams: 0.4,
      mainCategory: "ELECTRONICS" as const,
      subCategory: "RC_RECEIVER" as const,
      isComposite: false,
      integratedPartIds: [],
      isArchived: false,
      attributes: {},
    },
    {
      id: "rx-xmplus",
      name: "FrSky XM+ SBUS Mini Receiver",
      manufacturer: "FrSky",
      model: "XM+ SBUS",
      weightGrams: 1.6,
      mainCategory: "ELECTRONICS" as const,
      subCategory: "RC_RECEIVER" as const,
      isComposite: false,
      integratedPartIds: [],
      isArchived: false,
      attributes: {},
    },

    // ─── GPS MODULES (2 parts) ─────────────────────────────────────────────────
    {
      id: "gps-goku10",
      name: "GOKU GM10 Nano V3 GPS",
      manufacturer: "Flywoo",
      model: "GM10 Nano GPS",
      weightGrams: 2.2,
      mainCategory: "ELECTRONICS" as const,
      subCategory: "GPS" as const,
      isComposite: false,
      integratedPartIds: [],
      isArchived: false,
      attributes: {},
    },
    {
      id: "gps-matekm10",
      name: "Matek M10-5883 GPS & Compass Module",
      manufacturer: "Matek Systems",
      model: "M10-5883",
      weightGrams: 7.5,
      mainCategory: "ELECTRONICS" as const,
      subCategory: "GPS" as const,
      isComposite: false,
      integratedPartIds: [],
      isArchived: false,
      attributes: {},
    },

    // ─── CAMERAS (2 parts) ─────────────────────────────────────────────────────
    {
      id: "cam-phoenix2",
      name: "RunCam Phoenix 2 JB Edition FPV Camera",
      manufacturer: "RunCam",
      model: "Phoenix 2 JB",
      weightGrams: 9.0,
      mainCategory: "ELECTRONICS" as const,
      subCategory: "CAMERA" as const,
      isComposite: false,
      integratedPartIds: [],
      isArchived: false,
      attributes: {},
    },
    {
      id: "cam-ratel2",
      name: "Caddx Ratel 2 Micro Starlight FPV Camera",
      manufacturer: "Caddx",
      model: "Ratel 2",
      weightGrams: 6.0,
      mainCategory: "ELECTRONICS" as const,
      subCategory: "CAMERA" as const,
      isComposite: false,
      integratedPartIds: [],
      isArchived: false,
      attributes: {},
    },

    // ─── MISC ACCESSORIES (2 parts) ────────────────────────────────────────────
    {
      id: "strap-flywoo",
      name: "Flywoo Lipo Strap 15x250mm (Kevlar)",
      manufacturer: "Flywoo",
      model: "Battery Strap 250mm",
      weightGrams: 4.5,
      mainCategory: "ACCESSORIES" as const,
      subCategory: "BATTERY_STRAP" as const,
      isComposite: false,
      integratedPartIds: [],
      isArchived: false,
      attributes: {},
    },
    {
      id: "ant-foxeer",
      name: "Foxeer Lollipop 4 5.8G SMA Antenna",
      manufacturer: "Foxeer",
      model: "Lollipop 4 SMA",
      weightGrams: 8.2,
      mainCategory: "ELECTRONICS" as const,
      subCategory: "ANTENNA" as const,
      isComposite: false,
      integratedPartIds: [],
      isArchived: false,
      attributes: {},
    },
    // --- New custom parts requested by user ---
    {
      id: "frame-aether-archetype",
      name: "Aether Archetype 4\" Frame",
      manufacturer: "Aether FPV",
      model: "Archetype 4\"",
      weightGrams: 150.0,
      mainCategory: "FRAME" as const,
      subCategory: "FRAME" as const,
      isComposite: false,
      integratedPartIds: [],
      isArchived: false,
      attributes: {
        wheelbaseMm: 198.0,
        armThicknessMm: 5.0,
        maxPropSizeInch: 4.5,
        fcMountingPattern: ["20x20", "30.5x30.5"],
        motorMountingPattern: ["12x12"],
        vtxMountingPattern: ["20x20", "25.5x25.5"],
        stackHeightMaxMm: 25.0,
        topPlatePresent: true,
      },
    },
    {
      id: "fc-hdzero-halo-h7",
      name: "HDZero Halo H7 s ELRS Flight Controller",
      manufacturer: "HDZero",
      model: "Halo H7 FC",
      weightGrams: 5.6,
      mainCategory: "ELECTRONICS" as const,
      subCategory: "FC" as const,
      isComposite: false,
      integratedPartIds: [],
      isArchived: false,
      attributes: {
        mountingPattern: "20x20",
        inputVoltagesMax: 8,
        firmware: "Betaflight",
        gyro: "ICM-42688-P",
        mcu: "H7",
        uartCount: 6,
        hasBarometer: true,
        hasBluetooth: false,
        hasBec: true,
      },
    },
    {
      id: "esc-hdzero-halo-70a",
      name: "HDZero Halo 70A 8S AM32 ESC",
      manufacturer: "HDZero",
      model: "Halo 70A ESC",
      weightGrams: 7.8,
      mainCategory: "ELECTRONICS" as const,
      subCategory: "ESC" as const,
      isComposite: false,
      integratedPartIds: [],
      isArchived: false,
      attributes: {
        continuousCurrentAmps: 70.0,
        burstCurrentAmps: 100.0,
        mountingPattern: "20x20",
        inputVoltagesMax: 40,
        firmware: "AM32",
        motorOutputCount: 4,
        hasTelemetry: true,
      },
    },
    {
      id: "motor-gts2105-2950",
      name: "RCinpower GTS V3 2105 Plus 2950Kv Motor",
      manufacturer: "RCinpower",
      model: "GTS V3 2105 Plus 2950Kv",
      weightGrams: 21.0,
      mainCategory: "PROPULSION" as const,
      subCategory: "MOTOR" as const,
      isComposite: false,
      integratedPartIds: [],
      isArchived: false,
      attributes: {
        kv: 2950,
        statorDiameterMm: 21.0,
        statorHeightMm: 5.5,
        mountingPattern: "12x12",
        propMountingPattern: ["5mm"],
        inputVoltageMax: 16.8,
        maxCurrentDraw: 25.0,
      },
    },
    {
      id: "motor-gts2105-1850",
      name: "RCinpower GTS V3 2105 Plus 1850Kv Motor",
      manufacturer: "RCinpower",
      model: "GTS V3 2105 Plus 1850Kv",
      weightGrams: 20.0,
      mainCategory: "PROPULSION" as const,
      subCategory: "MOTOR" as const,
      isComposite: false,
      integratedPartIds: [],
      isArchived: false,
      attributes: {
        kv: 1850,
        statorDiameterMm: 21.0,
        statorHeightMm: 5.5,
        mountingPattern: "12x12",
        propMountingPattern: ["5mm"],
        inputVoltageMax: 25.2,
        maxCurrentDraw: 12.0,
      },
    },
    {
      id: "rx-flywoo-el24p",
      name: "Flywoo ELRS 2.4G EL24P TCXO Receiver",
      manufacturer: "Flywoo",
      model: "EL24P TCXO",
      weightGrams: 0.44,
      mainCategory: "ELECTRONICS" as const,
      subCategory: "RC_RECEIVER" as const,
      isComposite: false,
      integratedPartIds: [],
      isArchived: false,
      attributes: {},
    },
    {
      id: "prop-gemfan4525",
      name: "Gemfan Hurricane 4525 3-Blade Propeller",
      manufacturer: "Gemfan",
      model: "Hurricane 4525-3",
      weightGrams: 2.22,
      mainCategory: "PROPULSION" as const,
      subCategory: "PROPELLER" as const,
      isComposite: false,
      integratedPartIds: [],
      isArchived: false,
      attributes: {
        diameterInch: 4.5,
        pitchInch: 2.5,
        mountingPattern: ["5mm"],
        blades: 3,
      },
    },
    {
      id: "prop-gemfan4023",
      name: "Gemfan Hurricane 4023 3-Blade Propeller",
      manufacturer: "Gemfan",
      model: "Hurricane 4023-3",
      weightGrams: 1.98,
      mainCategory: "PROPULSION" as const,
      subCategory: "PROPELLER" as const,
      isComposite: false,
      integratedPartIds: [],
      isArchived: false,
      attributes: {
        diameterInch: 4.0,
        pitchInch: 2.3,
        mountingPattern: ["5mm"],
        blades: 3,
      },
    },
    {
      id: "prop-hq4030",
      name: "HQProp 4x3x3 V2 3-Blade Propeller",
      manufacturer: "HQProp",
      model: "4x3x3 V2",
      weightGrams: 2.2,
      mainCategory: "PROPULSION" as const,
      subCategory: "PROPELLER" as const,
      isComposite: false,
      integratedPartIds: [],
      isArchived: false,
      attributes: {
        diameterInch: 4.0,
        pitchInch: 3.0,
        mountingPattern: ["5mm"],
        blades: 3,
      },
    },
    {
      id: "prop-hq4025",
      name: "HQProp 4x2.5x3 V2S Durable 3-Blade Propeller",
      manufacturer: "HQProp",
      model: "4x2.5x3 V2S",
      weightGrams: 2.1,
      mainCategory: "PROPULSION" as const,
      subCategory: "PROPELLER" as const,
      isComposite: false,
      integratedPartIds: [],
      isArchived: false,
      attributes: {
        diameterInch: 4.0,
        pitchInch: 2.5,
        mountingPattern: ["5mm"],
        blades: 3,
      },
    },
    {
      id: "prop-gemfan4032",
      name: "Gemfan Windancer 4032 3-Blade Propeller",
      manufacturer: "Gemfan",
      model: "Windancer 4032-3",
      weightGrams: 3.12,
      mainCategory: "PROPULSION" as const,
      subCategory: "PROPELLER" as const,
      isComposite: false,
      integratedPartIds: [],
      isArchived: false,
      attributes: {
        diameterInch: 4.0,
        pitchInch: 3.2,
        mountingPattern: ["5mm"],
        blades: 3,
      },
    },
    {
      id: "vtx-flywoo-o4-wide",
      name: "Flywoo DJI O4 Wide Air Unit VTX",
      manufacturer: "Flywoo",
      model: "DJI O4 Wide",
      weightGrams: 21.5,
      mainCategory: "ELECTRONICS" as const,
      subCategory: "VTX" as const,
      isComposite: false,
      integratedPartIds: [],
      isArchived: false,
      attributes: {
        inputVoltageMin: 3.7,
        inputVoltageMax: 13.2,
        mountingPattern: ["20x20", "25.5x25.5"],
        maxPowerMw: 1000,
        protocol: "DJI O4",
      },
    },
    {
      id: "gps-hglrc-m100pro",
      name: "HGLRC M100 Pro GPS & Compass Module",
      manufacturer: "HGLRC",
      model: "M100 Pro",
      weightGrams: 7.9,
      mainCategory: "ELECTRONICS" as const,
      subCategory: "GPS" as const,
      isComposite: false,
      integratedPartIds: [],
      isArchived: false,
      attributes: {},
    },
    {
      id: "buzzer-flywoo-finder",
      name: "Flywoo Finder V1.0 Buzzer",
      manufacturer: "Flywoo",
      model: "Finder V1.0",
      weightGrams: 2.7,
      mainCategory: "ACCESSORIES" as const,
      subCategory: "BUZZER" as const,
      isComposite: false,
      integratedPartIds: [],
      isArchived: false,
      attributes: {},
    },
    {
      id: "bat-cnhl1100-4s",
      name: "CNHL Black Series 4S 1100mAh 130C LiPo",
      manufacturer: "CNHL",
      model: "Black Series 4S 1100mAh",
      weightGrams: 140.0,
      mainCategory: "PROPULSION" as const,
      subCategory: "BATTERY" as const,
      isComposite: false,
      integratedPartIds: [],
      isArchived: false,
      attributes: {
        cellCount: 4,
        capacityMah: 1100.0,
        cRating: 130,
        chemistry: "LiPo",
      },
    },
  ];

  // Batch insert all parts
  for (const part of seededParts) {
    await db.insert(parts).values({
      id: part.id,
      name: part.name,
      manufacturer: part.manufacturer,
      model: part.model,
      weightGrams: part.weightGrams,
      mainCategory: part.mainCategory,
      subCategory: part.subCategory,
      isComposite: part.isComposite,
      integratedPartIds: part.integratedPartIds,
      isArchived: part.isArchived,
      attributes: part.attributes,
    });
  }

  console.log(`Successfully seeded ${seededParts.length} parts.`);

  // 3. Insert Thrust Test Data
  const seededThrustTests = [
    // Xing2 2207 1850KV (motor-xing2207-1850) + Gemfan Hurricane 51433 (prop-gemfan51433) + 6S LiPo
    {
      id: "thrust-xing2207-gf51433-6s",
      motorId: "motor-xing2207-1850",
      propellerId: "prop-gemfan51433",
      batteryCellCount: 6,
      batteryChemistry: "LiPo" as const,
      isEmpirical: true,
      sourceLabel: "RCBenchmark Stand V3 export 2026-04-12",
      testPoints: [
        { throttlePercent: 0, currentAmps: 0.0, thrustGrams: 0, voltageVolts: 25.2, rpm: 0 },
        { throttlePercent: 10, currentAmps: 1.5, thrustGrams: 110, voltageVolts: 24.8, rpm: 8000 },
        { throttlePercent: 20, currentAmps: 3.5, thrustGrams: 250, voltageVolts: 24.6, rpm: 13000 },
        { throttlePercent: 30, currentAmps: 7.2, thrustGrams: 420, voltageVolts: 24.4, rpm: 18000 },
        { throttlePercent: 40, currentAmps: 12.0, thrustGrams: 610, voltageVolts: 24.1, rpm: 22500 },
        { throttlePercent: 50, currentAmps: 18.5, thrustGrams: 840, voltageVolts: 23.7, rpm: 26500 },
        { throttlePercent: 60, currentAmps: 26.0, thrustGrams: 1080, voltageVolts: 23.2, rpm: 30500 },
        { throttlePercent: 70, currentAmps: 35.0, thrustGrams: 1320, voltageVolts: 22.8, rpm: 33500 },
        { throttlePercent: 80, currentAmps: 45.0, thrustGrams: 1580, voltageVolts: 22.3, rpm: 36500 },
        { throttlePercent: 90, currentAmps: 56.0, thrustGrams: 1850, voltageVolts: 21.8, rpm: 39000 },
        { throttlePercent: 100, currentAmps: 68.0, thrustGrams: 2120, voltageVolts: 21.2, rpm: 41200 },
      ],
    },
    // Velox V3 2207 1950KV (motor-velox2207) + Gemfan Hurricane 51433 (prop-gemfan51433) + 6S LiPo
    {
      id: "thrust-velox2207-gf51433-6s",
      motorId: "motor-velox2207",
      propellerId: "prop-gemfan51433",
      batteryCellCount: 6,
      batteryChemistry: "LiPo" as const,
      isEmpirical: true,
      sourceLabel: "T-Motor official datasheet 2025",
      testPoints: [
        { throttlePercent: 0, currentAmps: 0.0, thrustGrams: 0, voltageVolts: 25.2, rpm: 0 },
        { throttlePercent: 10, currentAmps: 1.8, thrustGrams: 120, voltageVolts: 24.8, rpm: 8500 },
        { throttlePercent: 20, currentAmps: 4.2, thrustGrams: 280, voltageVolts: 24.6, rpm: 14000 },
        { throttlePercent: 30, currentAmps: 8.5, thrustGrams: 450, voltageVolts: 24.3, rpm: 19000 },
        { throttlePercent: 40, currentAmps: 13.8, thrustGrams: 660, voltageVolts: 24.0, rpm: 23500 },
        { throttlePercent: 50, currentAmps: 20.0, thrustGrams: 890, voltageVolts: 23.6, rpm: 27500 },
        { throttlePercent: 60, currentAmps: 28.5, thrustGrams: 1140, voltageVolts: 23.1, rpm: 31500 },
        { throttlePercent: 70, currentAmps: 38.0, thrustGrams: 1380, voltageVolts: 22.7, rpm: 34500 },
        { throttlePercent: 80, currentAmps: 48.5, thrustGrams: 1650, voltageVolts: 22.1, rpm: 37500 },
        { throttlePercent: 90, currentAmps: 60.0, thrustGrams: 1950, voltageVolts: 21.6, rpm: 40000 },
        { throttlePercent: 100, currentAmps: 72.0, thrustGrams: 2250, voltageVolts: 21.0, rpm: 42500 },
      ],
    },
    // HappyModel SE0802 19000KV (motor-se0802) + Gemfan 1635 40mm Whoop Prop (prop-gemfan1635) + 1S LiHv
    {
      id: "thrust-se0802-gf1635-1s",
      motorId: "motor-se0802",
      propellerId: "prop-gemfan1635",
      batteryCellCount: 1,
      batteryChemistry: "LiHv" as const,
      isEmpirical: true,
      sourceLabel: "HappyModel custom lab test",
      testPoints: [
        { throttlePercent: 0, currentAmps: 0.0, thrustGrams: 0, voltageVolts: 4.35, rpm: 0 },
        { throttlePercent: 10, currentAmps: 0.15, thrustGrams: 3.5, voltageVolts: 4.3, rpm: 6000 },
        { throttlePercent: 20, currentAmps: 0.4, thrustGrams: 7.2, voltageVolts: 4.23, rpm: 12000 },
        { throttlePercent: 30, currentAmps: 0.8, thrustGrams: 12.0, voltageVolts: 4.15, rpm: 18000 },
        { throttlePercent: 40, currentAmps: 1.25, thrustGrams: 18.0, voltageVolts: 4.05, rpm: 24000 },
        { throttlePercent: 50, currentAmps: 1.8, thrustGrams: 25.0, voltageVolts: 3.95, rpm: 30000 },
        { throttlePercent: 60, currentAmps: 2.45, thrustGrams: 31.0, voltageVolts: 3.85, rpm: 36000 },
        { throttlePercent: 70, currentAmps: 3.2, thrustGrams: 38.0, voltageVolts: 3.75, rpm: 41000 },
        { throttlePercent: 80, currentAmps: 3.9, thrustGrams: 44.0, voltageVolts: 3.65, rpm: 46000 },
        { throttlePercent: 90, currentAmps: 4.7, thrustGrams: 49.0, voltageVolts: 3.58, rpm: 51000 },
        { throttlePercent: 100, currentAmps: 5.5, thrustGrams: 54.0, voltageVolts: 3.5, rpm: 55000 },
      ],
    },
    // GTS V3 2105plus-1850KV (motor-gts2105-1850) + Gemfan Hurricane 4023-3 (prop-gemfan4023) + 6S LiPo
    {
      id: "thrust-gts2105-1850-gf4023-6s",
      motorId: "motor-gts2105-1850",
      propellerId: "prop-gemfan4023",
      batteryCellCount: 6,
      batteryChemistry: "LiPo" as const,
      isEmpirical: true,
      sourceLabel: "RCBenchmark Stand V3 export 2026-06",
      testPoints: [
        { throttlePercent: 0, currentAmps: 0.0, thrustGrams: 0, voltageVolts: 24.0, rpm: 0 },
        { throttlePercent: 10, currentAmps: 0.32, thrustGrams: 36, voltageVolts: 24.0, rpm: 0 },
        { throttlePercent: 20, currentAmps: 0.64, thrustGrams: 72, voltageVolts: 24.0, rpm: 0 },
        { throttlePercent: 30, currentAmps: 0.96, thrustGrams: 109, voltageVolts: 24.0, rpm: 0 },
        { throttlePercent: 40, currentAmps: 1.28, thrustGrams: 145, voltageVolts: 24.0, rpm: 0 },
        { throttlePercent: 50, currentAmps: 1.6, thrustGrams: 181, voltageVolts: 24.0, rpm: 0 },
        { throttlePercent: 60, currentAmps: 3.06, thrustGrams: 266, voltageVolts: 24.0, rpm: 0 },
        { throttlePercent: 70, currentAmps: 4.52, thrustGrams: 350, voltageVolts: 24.0, rpm: 0 },
        { throttlePercent: 80, currentAmps: 5.98, thrustGrams: 435, voltageVolts: 24.0, rpm: 0 },
        { throttlePercent: 90, currentAmps: 7.44, thrustGrams: 519, voltageVolts: 24.0, rpm: 0 },
        { throttlePercent: 100, currentAmps: 8.9, thrustGrams: 604, voltageVolts: 24.0, rpm: 0 },
      ],
    },
    // GTS V3 2105plus-1850KV (motor-gts2105-1850) + HQProp 4x2.5x3 V2S (prop-hq4025) + 6S LiPo
    {
      id: "thrust-gts2105-1850-hq4025-6s",
      motorId: "motor-gts2105-1850",
      propellerId: "prop-hq4025",
      batteryCellCount: 6,
      batteryChemistry: "LiPo" as const,
      isEmpirical: true,
      sourceLabel: "RCBenchmark Stand V3 export 2026-06",
      testPoints: [
        { throttlePercent: 0, currentAmps: 0.0, thrustGrams: 0, voltageVolts: 24.0, rpm: 0 },
        { throttlePercent: 10, currentAmps: 0.8, thrustGrams: 38, voltageVolts: 24.0, rpm: 0 },
        { throttlePercent: 20, currentAmps: 1.0, thrustGrams: 76, voltageVolts: 24.0, rpm: 0 },
        { throttlePercent: 30, currentAmps: 1.2, thrustGrams: 114, voltageVolts: 24.0, rpm: 0 },
        { throttlePercent: 40, currentAmps: 1.4, thrustGrams: 152, voltageVolts: 24.0, rpm: 0 },
        { throttlePercent: 50, currentAmps: 1.6, thrustGrams: 190, voltageVolts: 24.0, rpm: 0 },
        { throttlePercent: 60, currentAmps: 3.12, thrustGrams: 277, voltageVolts: 24.0, rpm: 0 },
        { throttlePercent: 70, currentAmps: 4.64, thrustGrams: 364, voltageVolts: 24.0, rpm: 0 },
        { throttlePercent: 80, currentAmps: 6.16, thrustGrams: 452, voltageVolts: 24.0, rpm: 0 },
        { throttlePercent: 90, currentAmps: 7.68, thrustGrams: 539, voltageVolts: 24.0, rpm: 0 },
        { throttlePercent: 100, currentAmps: 9.2, thrustGrams: 626, voltageVolts: 24.0, rpm: 0 },
      ],
    },
    // GTS V3 2105plus-1850KV (motor-gts2105-1850) + HQProp 4x3x3 V2 (prop-hq4030) + 6S LiPo
    {
      id: "thrust-gts2105-1850-hq4030-6s",
      motorId: "motor-gts2105-1850",
      propellerId: "prop-hq4030",
      batteryCellCount: 6,
      batteryChemistry: "LiPo" as const,
      isEmpirical: true,
      sourceLabel: "RCBenchmark Stand V3 export 2026-06",
      testPoints: [
        { throttlePercent: 0, currentAmps: 0.0, thrustGrams: 0, voltageVolts: 24.0, rpm: 0 },
        { throttlePercent: 10, currentAmps: 0.36, thrustGrams: 42, voltageVolts: 24.0, rpm: 0 },
        { throttlePercent: 20, currentAmps: 0.72, thrustGrams: 84, voltageVolts: 24.0, rpm: 0 },
        { throttlePercent: 30, currentAmps: 1.08, thrustGrams: 126, voltageVolts: 24.0, rpm: 0 },
        { throttlePercent: 40, currentAmps: 1.44, thrustGrams: 168, voltageVolts: 24.0, rpm: 0 },
        { throttlePercent: 50, currentAmps: 1.8, thrustGrams: 210, voltageVolts: 24.0, rpm: 0 },
        { throttlePercent: 60, currentAmps: 3.42, thrustGrams: 303, voltageVolts: 24.0, rpm: 0 },
        { throttlePercent: 70, currentAmps: 5.04, thrustGrams: 397, voltageVolts: 24.0, rpm: 0 },
        { throttlePercent: 80, currentAmps: 6.66, thrustGrams: 490, voltageVolts: 24.0, rpm: 0 },
        { throttlePercent: 90, currentAmps: 8.28, thrustGrams: 584, voltageVolts: 24.0, rpm: 0 },
        { throttlePercent: 100, currentAmps: 9.9, thrustGrams: 677, voltageVolts: 24.0, rpm: 0 },
      ],
    },
    // GTS V3 2105plus-1850KV (motor-gts2105-1850) + Gemfan Windancer 4032-3 (prop-gemfan4032) + 6S LiPo
    {
      id: "thrust-gts2105-1850-gf4032-6s",
      motorId: "motor-gts2105-1850",
      propellerId: "prop-gemfan4032",
      batteryCellCount: 6,
      batteryChemistry: "LiPo" as const,
      isEmpirical: true,
      sourceLabel: "RCBenchmark Stand V3 export 2026-06",
      testPoints: [
        { throttlePercent: 0, currentAmps: 0.0, thrustGrams: 0, voltageVolts: 24.0, rpm: 0 },
        { throttlePercent: 10, currentAmps: 0.38, thrustGrams: 43, voltageVolts: 24.0, rpm: 0 },
        { throttlePercent: 20, currentAmps: 0.76, thrustGrams: 87, voltageVolts: 24.0, rpm: 0 },
        { throttlePercent: 30, currentAmps: 1.14, thrustGrams: 130, voltageVolts: 24.0, rpm: 0 },
        { throttlePercent: 40, currentAmps: 1.52, thrustGrams: 174, voltageVolts: 24.0, rpm: 0 },
        { throttlePercent: 50, currentAmps: 1.9, thrustGrams: 217, voltageVolts: 24.0, rpm: 0 },
        { throttlePercent: 60, currentAmps: 3.56, thrustGrams: 313, voltageVolts: 24.0, rpm: 0 },
        { throttlePercent: 70, currentAmps: 5.22, thrustGrams: 409, voltageVolts: 24.0, rpm: 0 },
        { throttlePercent: 80, currentAmps: 6.88, thrustGrams: 506, voltageVolts: 24.0, rpm: 0 },
        { throttlePercent: 90, currentAmps: 8.54, thrustGrams: 602, voltageVolts: 24.0, rpm: 0 },
        { throttlePercent: 100, currentAmps: 10.2, thrustGrams: 698, voltageVolts: 24.0, rpm: 0 },
      ],
    },
    // GTS V3 2105plus-1850KV (motor-gts2105-1850) + Gemfan Hurricane 4525-3 (prop-gemfan4525) + 6S LiPo
    {
      id: "thrust-gts2105-1850-gf4525-6s",
      motorId: "motor-gts2105-1850",
      propellerId: "prop-gemfan4525",
      batteryCellCount: 6,
      batteryChemistry: "LiPo" as const,
      isEmpirical: true,
      sourceLabel: "RCBenchmark Stand V3 export 2026-06",
      testPoints: [
        { throttlePercent: 0, currentAmps: 0.0, thrustGrams: 0, voltageVolts: 24.0, rpm: 0 },
        { throttlePercent: 10, currentAmps: 0.4, thrustGrams: 48, voltageVolts: 24.0, rpm: 0 },
        { throttlePercent: 20, currentAmps: 0.8, thrustGrams: 96, voltageVolts: 24.0, rpm: 0 },
        { throttlePercent: 30, currentAmps: 1.2, thrustGrams: 143, voltageVolts: 24.0, rpm: 0 },
        { throttlePercent: 40, currentAmps: 1.6, thrustGrams: 191, voltageVolts: 24.0, rpm: 0 },
        { throttlePercent: 50, currentAmps: 2.0, thrustGrams: 239, voltageVolts: 24.0, rpm: 0 },
        { throttlePercent: 60, currentAmps: 3.78, thrustGrams: 340, voltageVolts: 24.0, rpm: 0 },
        { throttlePercent: 70, currentAmps: 5.56, thrustGrams: 442, voltageVolts: 24.0, rpm: 0 },
        { throttlePercent: 80, currentAmps: 7.34, thrustGrams: 543, voltageVolts: 24.0, rpm: 0 },
        { throttlePercent: 90, currentAmps: 9.12, thrustGrams: 645, voltageVolts: 24.0, rpm: 0 },
        { throttlePercent: 100, currentAmps: 10.9, thrustGrams: 746, voltageVolts: 24.0, rpm: 0 },
      ],
    },
    // GTS V3 2105plus-2950KV (motor-gts2105-2950) + Gemfan Hurricane 4023-3 (prop-gemfan4023) + 4S LiPo
    {
      id: "thrust-gts2105-2950-gf4023-4s",
      motorId: "motor-gts2105-2950",
      propellerId: "prop-gemfan4023",
      batteryCellCount: 4,
      batteryChemistry: "LiPo" as const,
      isEmpirical: true,
      sourceLabel: "RCBenchmark Stand V3 export 2026-06",
      testPoints: [
        { throttlePercent: 0, currentAmps: 0.0, thrustGrams: 0, voltageVolts: 16.0, rpm: 0 },
        { throttlePercent: 10, currentAmps: 0.78, thrustGrams: 50, voltageVolts: 16.0, rpm: 0 },
        { throttlePercent: 20, currentAmps: 1.56, thrustGrams: 100, voltageVolts: 16.0, rpm: 0 },
        { throttlePercent: 30, currentAmps: 2.34, thrustGrams: 151, voltageVolts: 16.0, rpm: 0 },
        { throttlePercent: 40, currentAmps: 3.12, thrustGrams: 201, voltageVolts: 16.0, rpm: 0 },
        { throttlePercent: 50, currentAmps: 3.9, thrustGrams: 251, voltageVolts: 16.0, rpm: 0 },
        { throttlePercent: 60, currentAmps: 6.96, thrustGrams: 360, voltageVolts: 16.0, rpm: 0 },
        { throttlePercent: 70, currentAmps: 10.02, thrustGrams: 469, voltageVolts: 16.0, rpm: 0 },
        { throttlePercent: 80, currentAmps: 13.08, thrustGrams: 577, voltageVolts: 16.0, rpm: 0 },
        { throttlePercent: 90, currentAmps: 16.14, thrustGrams: 686, voltageVolts: 16.0, rpm: 0 },
        { throttlePercent: 100, currentAmps: 19.2, thrustGrams: 795, voltageVolts: 16.0, rpm: 0 },
      ],
    },
    // GTS V3 2105plus-2950KV (motor-gts2105-2950) + HQProp 4x2.5x3 V2S (prop-hq4025) + 4S LiPo
    {
      id: "thrust-gts2105-2950-hq4025-4s",
      motorId: "motor-gts2105-2950",
      propellerId: "prop-hq4025",
      batteryCellCount: 4,
      batteryChemistry: "LiPo" as const,
      isEmpirical: true,
      sourceLabel: "RCBenchmark Stand V3 export 2026-06",
      testPoints: [
        { throttlePercent: 0, currentAmps: 0.0, thrustGrams: 0, voltageVolts: 16.0, rpm: 0 },
        { throttlePercent: 10, currentAmps: 0.82, thrustGrams: 53, voltageVolts: 16.0, rpm: 0 },
        { throttlePercent: 20, currentAmps: 1.64, thrustGrams: 106, voltageVolts: 16.0, rpm: 0 },
        { throttlePercent: 30, currentAmps: 2.46, thrustGrams: 158, voltageVolts: 16.0, rpm: 0 },
        { throttlePercent: 40, currentAmps: 3.28, thrustGrams: 211, voltageVolts: 16.0, rpm: 0 },
        { throttlePercent: 50, currentAmps: 4.1, thrustGrams: 264, voltageVolts: 16.0, rpm: 0 },
        { throttlePercent: 60, currentAmps: 7.28, thrustGrams: 376, voltageVolts: 16.0, rpm: 0 },
        { throttlePercent: 70, currentAmps: 10.46, thrustGrams: 488, voltageVolts: 16.0, rpm: 0 },
        { throttlePercent: 80, currentAmps: 13.64, thrustGrams: 600, voltageVolts: 16.0, rpm: 0 },
        { throttlePercent: 90, currentAmps: 16.82, thrustGrams: 712, voltageVolts: 16.0, rpm: 0 },
        { throttlePercent: 100, currentAmps: 20.0, thrustGrams: 824, voltageVolts: 16.0, rpm: 0 },
      ],
    },
    // GTS V3 2105plus-2950KV (motor-gts2105-2950) + HQProp 4x3x3 V2 (prop-hq4030) + 4S LiPo
    {
      id: "thrust-gts2105-2950-hq4030-4s",
      motorId: "motor-gts2105-2950",
      propellerId: "prop-hq4030",
      batteryCellCount: 4,
      batteryChemistry: "LiPo" as const,
      isEmpirical: true,
      sourceLabel: "RCBenchmark Stand V3 export 2026-06",
      testPoints: [
        { throttlePercent: 0, currentAmps: 0.0, thrustGrams: 0, voltageVolts: 16.0, rpm: 0 },
        { throttlePercent: 10, currentAmps: 0.92, thrustGrams: 59, voltageVolts: 16.0, rpm: 0 },
        { throttlePercent: 20, currentAmps: 1.84, thrustGrams: 117, voltageVolts: 16.0, rpm: 0 },
        { throttlePercent: 30, currentAmps: 2.76, thrustGrams: 176, voltageVolts: 16.0, rpm: 0 },
        { throttlePercent: 40, currentAmps: 3.68, thrustGrams: 234, voltageVolts: 16.0, rpm: 0 },
        { throttlePercent: 50, currentAmps: 4.6, thrustGrams: 293, voltageVolts: 16.0, rpm: 0 },
        { throttlePercent: 60, currentAmps: 8.06, thrustGrams: 412, voltageVolts: 16.0, rpm: 0 },
        { throttlePercent: 70, currentAmps: 11.52, thrustGrams: 531, voltageVolts: 16.0, rpm: 0 },
        { throttlePercent: 80, currentAmps: 14.98, thrustGrams: 651, voltageVolts: 16.0, rpm: 0 },
        { throttlePercent: 90, currentAmps: 18.44, thrustGrams: 770, voltageVolts: 16.0, rpm: 0 },
        { throttlePercent: 100, currentAmps: 21.9, thrustGrams: 889, voltageVolts: 16.0, rpm: 0 },
      ],
    },
    // GTS V3 2105plus-2950KV (motor-gts2105-2950) + Gemfan Windancer 4032-3 (prop-gemfan4032) + 4S LiPo
    {
      id: "thrust-gts2105-2950-gf4032-4s",
      motorId: "motor-gts2105-2950",
      propellerId: "prop-gemfan4032",
      batteryCellCount: 4,
      batteryChemistry: "LiPo" as const,
      isEmpirical: true,
      sourceLabel: "RCBenchmark Stand V3 export 2026-06",
      testPoints: [
        { throttlePercent: 0, currentAmps: 0.0, thrustGrams: 0, voltageVolts: 16.0, rpm: 0 },
        { throttlePercent: 10, currentAmps: 0.94, thrustGrams: 61, voltageVolts: 16.0, rpm: 0 },
        { throttlePercent: 20, currentAmps: 1.88, thrustGrams: 121, voltageVolts: 16.0, rpm: 0 },
        { throttlePercent: 30, currentAmps: 2.82, thrustGrams: 182, voltageVolts: 16.0, rpm: 0 },
        { throttlePercent: 40, currentAmps: 3.76, thrustGrams: 243, voltageVolts: 16.0, rpm: 0 },
        { throttlePercent: 50, currentAmps: 4.7, thrustGrams: 304, voltageVolts: 16.0, rpm: 0 },
        { throttlePercent: 60, currentAmps: 8.28, thrustGrams: 426, voltageVolts: 16.0, rpm: 0 },
        { throttlePercent: 70, currentAmps: 11.86, thrustGrams: 548, voltageVolts: 16.0, rpm: 0 },
        { throttlePercent: 80, currentAmps: 15.44, thrustGrams: 669, voltageVolts: 16.0, rpm: 0 },
        { throttlePercent: 90, currentAmps: 19.02, thrustGrams: 791, voltageVolts: 16.0, rpm: 0 },
        { throttlePercent: 100, currentAmps: 22.6, thrustGrams: 913, voltageVolts: 16.0, rpm: 0 },
      ],
    },
    // GTS V3 2105plus-2950KV (motor-gts2105-2950) + Gemfan Hurricane 4525-3 (prop-gemfan4525) + 4S LiPo
    {
      id: "thrust-gts2105-2950-gf4525-4s",
      motorId: "motor-gts2105-2950",
      propellerId: "prop-gemfan4525",
      batteryCellCount: 4,
      batteryChemistry: "LiPo" as const,
      isEmpirical: true,
      sourceLabel: "RCBenchmark Stand V3 export 2026-06",
      testPoints: [
        { throttlePercent: 0, currentAmps: 0.0, thrustGrams: 0, voltageVolts: 16.0, rpm: 0 },
        { throttlePercent: 10, currentAmps: 1.04, thrustGrams: 67, voltageVolts: 16.0, rpm: 0 },
        { throttlePercent: 20, currentAmps: 2.08, thrustGrams: 134, voltageVolts: 16.0, rpm: 0 },
        { throttlePercent: 30, currentAmps: 3.12, thrustGrams: 200, voltageVolts: 16.0, rpm: 0 },
        { throttlePercent: 40, currentAmps: 4.16, thrustGrams: 267, voltageVolts: 16.0, rpm: 0 },
        { throttlePercent: 50, currentAmps: 5.2, thrustGrams: 334, voltageVolts: 16.0, rpm: 0 },
        { throttlePercent: 60, currentAmps: 9.06, thrustGrams: 463, voltageVolts: 16.0, rpm: 0 },
        { throttlePercent: 70, currentAmps: 12.92, thrustGrams: 592, voltageVolts: 16.0, rpm: 0 },
        { throttlePercent: 80, currentAmps: 16.78, thrustGrams: 720, voltageVolts: 16.0, rpm: 0 },
        { throttlePercent: 90, currentAmps: 20.64, thrustGrams: 849, voltageVolts: 16.0, rpm: 0 },
        { throttlePercent: 100, currentAmps: 24.5, thrustGrams: 978, voltageVolts: 16.0, rpm: 0 },
      ],
    },
  ];

  for (const t of seededThrustTests) {
    await db.insert(thrustTestData).values({
      id: t.id,
      motorId: t.motorId,
      propellerId: t.propellerId,
      batteryCellCount: t.batteryCellCount,
      batteryChemistry: t.batteryChemistry,
      isEmpirical: t.isEmpirical,
      sourceLabel: t.sourceLabel,
      testPoints: t.testPoints,
    });
  }

  console.log("Seeding complete! Database is ready.");

  // Write seed data to Seed/ directory for production import
  try {
    const seedDir = path.join(__dirname, "../../../Seed");
    if (!fs.existsSync(seedDir)) {
      fs.mkdirSync(seedDir, { recursive: true });
    }

    // 1. Write parts.json
    fs.writeFileSync(
      path.join(seedDir, "parts.json"),
      JSON.stringify({ parts: seededParts }, null, 2),
      "utf-8"
    );
    console.log("Exported Seed/parts.json");

    // 2. Write thrust_tests.json
    fs.writeFileSync(
      path.join(seedDir, "thrust_tests.json"),
      JSON.stringify({ tests: seededThrustTests }, null, 2),
      "utf-8"
    );
    console.log("Exported Seed/thrust_tests.json");

  } catch (exportErr) {
    console.error("Failed to export seed files: ", exportErr);
  }

  await db.run(sql`PRAGMA foreign_keys = ON;`);
}

main().catch((err) => {
  console.error("Failed to seed database: ", err);
  process.exit(1);
});
